### ISSUE TITLE
Battery holder

### ISSUE THREAD

**Issue by TAGood827** [designer2k2/2d-xmas-tree#1]
Thanks for sharing this project! Just wondering if there was a specific battery holder used in the design? I'm thinking about designing a rear stand sort of thing for a couple to be able to sit on a table.

**Comment by designer2k2** [comment]
Hello,
the Battery holder has to be made with thin wire: https://github.com/designer2k2/2d-xmas-tree/wiki#Battery

Construction is in the video from 5:12 onwards: https://www.youtube.com/watch?v=K6z7--RqQHQ

The lower side from the PCB has 2 exposed vias, there you can solder in a piece of thick copper wire to make a simple stand:
![grafik](https://user-images.githubusercontent.com/1591573/52538161-83f4f780-2d6f-11e9-8831-05cf192456a5.png)
