### ISSUE TITLE
Should we update year on the front side?

### ISSUE THREAD

**Issue by kasedy** [designer2k2/2d-xmas-tree#2]
There is 2018 label on the front side. Should we update it to 2020 or make it smaller and move to a side as a designing/manufacturing year?

**Comment by designer2k2** [comment]
Hello,
you can modify it to your liking, for me it will stay as my 2018 xmas project.

There is my 2016 digistump tree: https://github.com/designer2k2/xmas-tree
And the 2017 raspberry pi tree: https://www.designer2k2.at/en/mods/elektronik/134-overpowered-raspberry-pi-xmas-led-tree
